// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApi.Models
{
    public partial class Equipe
    {
        public Equipe()
        {
            Joueurs = new HashSet<Joueur>();
        }

        public int Id { get; set; }
        public string NomE { get; set; }

        public virtual ICollection<Joueur> Joueurs { get; set; }
    }
}