// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WebApi.Models;

namespace WebApi.Data
{
    public partial class TournoiDBContext : DbContext
    {
        public TournoiDBContext()
        {
        }

        public TournoiDBContext(DbContextOptions<TournoiDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Equipe> Equipes { get; set; }
        public virtual DbSet<Joueur> Joueurs { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Equipe>(entity =>
            {
                entity.ToTable("Equipe");

                entity.Property(e => e.NomE)
                    .HasMaxLength(50)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Joueur>(entity =>
            {
                entity.ToTable("Joueur");

                entity.Property(e => e.IdE).HasColumnName("Id_E");

                entity.Property(e => e.NomJ)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.SexeJ)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.HasOne(d => d.IdENavigation)
                    .WithMany(p => p.Joueurs)
                    .HasForeignKey(d => d.IdE)
                    .HasConstraintName("FK_Joueur_Equipe");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}